export const BOOTSTRAP_MODULE_OPTIONS = 'BOOTSTRAP_MODULE_OPTIONS';
export const BOOTSTRAP_CONFIGURATION_OPTIONS =
  'BOOTSTRAP_CONFIGURATION_OPTIONS';
export const BOOTSTRAP_VALUE = 'BOOTSTRAP_VALUE';
