export const RESOLVE_REFERENCE_METADATA = Symbol('RESOLVE_REFERENCE_METADATA');
export const DISTRIBUTED_GATEWAY_OPTIONS = Symbol('DISTRIBUTED_GATEWAY_OPTIONS');
export const DISTRIBUTED_GATEWAY_BUILD_SERVICE = Symbol('DISTRIBUTED_GATEWAY_BUILD_SERVICE');

export const RESOLVE_REFERENCE_KEY = '__resolveReference';
