import 'jest-ts-auto-mock';

module.exports = {
  projects: [
    '<rootDir>/packages/cloud',
    '<rootDir>/packages/proto-schema',
    '<rootDir>/packages/core',
    '<rootDir>/packages/common',
    '<rootDir>/packages/loadbalancer',
    '<rootDir>/packages/permissions',
    '<rootDir>/packages/cli',
    '<rootDir>/examples/example',
    '<rootDir>/examples/adv-example',
    '<rootDir>/packages/consul',
    '<rootDir>/packages/zookeeper',
    '<rootDir>/packages/etcd',
    '<rootDir>/packages/config',
    '<rootDir>/packages/messaging',
    '<rootDir>/packages/redis',
    '<rootDir>/packages/event-store',
    '<rootDir>/packages/couchbase',
    '<rootDir>/packages/client',
    '<rootDir>/packages/brakes',
    '<rootDir>/examples/event-store-example',
    '<rootDir>/packages/plugin-nx',
    '<rootDir>/examples/plugin-nx-e2e',
    '<rootDir>/packages/gateway',
    '<rootDir>/packages/create-ub-project',
    '<rootDir>/packages/bootstrap',
    '<rootDir>/packages/kubernetes',
  ],
};
