export const DATABASE_CONNECTIONS_CONTAINER = 'DatabaseConnectionsContainer';
export const DATABASE_CONTAINER_NAME = 'DatabaseContainerName';
export const DATABASE_CONNECTION_NAME = 'DatabaseConnectionName';
export const DATABASE_MODULE_OPTIONS = 'DatabaseModuleOptions';

export const DEFAULT_DATABASE_CONTAINER_NAME = 'DefaultDatabase';
export const CURRENT_TENANT_CONTAINER = 'CurrentTenant';
export const DEFAULT_DATABASE_CONNECTION_NAME = 'DefaultDatabase';

export const ARANGO_DATABASE_CONNECTIONS_CONTAINER =
  'Arango' + DATABASE_CONNECTIONS_CONTAINER;
export const ARANGO_DATABASE_CONTAINER_NAME =
  'Arango' + DATABASE_CONTAINER_NAME;
export const ARANGO_DATABASE_CONNECTION_NAME =
  'Arango' + DATABASE_CONNECTION_NAME;
export const ARANGO_DATABASE_MODULE_OPTIONS =
  'Arango' + DATABASE_MODULE_OPTIONS;

export const ARANGO_DEFAULT_DATABASE_CONTAINER_NAME =
  'Arango' + DEFAULT_DATABASE_CONTAINER_NAME;
export const ARANGO_DEFAULT_DATABASE_CONNECTION_NAME =
  'Arango' + DEFAULT_DATABASE_CONNECTION_NAME;

export const RAVEN_DATABASE_CONNECTIONS_CONTAINER =
  'Raven' + DATABASE_CONNECTIONS_CONTAINER;
export const RAVEN_DATABASE_CONTAINER_NAME = 'Raven' + DATABASE_CONTAINER_NAME;
export const RAVEN_DATABASE_CONNECTION_NAME =
  'Raven' + DATABASE_CONNECTION_NAME;
export const RAVEN_DATABASE_MODULE_OPTIONS = 'Raven' + DATABASE_MODULE_OPTIONS;

export const RAVEN_DEFAULT_DATABASE_CONTAINER_NAME =
  'Raven' + DEFAULT_DATABASE_CONTAINER_NAME;
export const RAVEN_DEFAULT_DATABASE_CONNECTION_NAME =
  'Raven' + DEFAULT_DATABASE_CONNECTION_NAME;
