export const TENANT_SERVICE = 'TENANT_SERVICE_ACCESS';
export const AUTH_SERVICE = 'AUTH_SERVICE_ACCESS';
export const ROLE_SERVICE = 'ROLE_SERVICE_ACCESS';

export const BILLING_SERVICE = 'BILLING_SERVICE_ACCESS';
export const PAYMENT_SERVICE = 'PAYMENT_SERVICE_ACCESS';
export const USER_SERVICE = 'USER_SERVICE_ACCESS';

export const INVOICE_SERVICE = 'INVOICE_SERVICE_ACCESS';
export const SUBSCRIPTION_SERVICE = 'SUBSCRIPTION_SERVICE_ACCESS';
export const NOTIFICATION_SERVICE = 'USER_SERVICE_ACCESS';
